### ISSUE TITLE
Licence ?

### ISSUE THREAD

**Issue by julientaq** [Iconscout/unicons#1]
Hey!

This is a pretty neat work :)

What is the licence for those icons?
I believe that the repo needs some Licence.md so people can know how they can use it.

Thanks!

**Comment by tarunmangukiya** [comment]
Hi @julientaq,

Thanks for drawing attention! We've added Apache-2.0 license here https://github.com/Iconscout/unicons/blob/master/LICENSE. Feel free to use the icons for your commercial projects.

Best,
Tarun
