### ISSUE TITLE
AccessDenied While Using The https://unicons.iconscout.com/release/v3.0.1/css/unicons.css

### ISSUE THREAD

**Issue by coderkali** [Iconscout/unicons#111]
I am unable to add to my Project using below link getting Acces denied 

https://unicons.iconscout.com/release/v3.0.1/css/unicons.css.

Please fix it or give the css to workaround.

**Comment by PaulJacobs-percona** [comment]
https://unicons.iconscout.com/release/v2.1.0/css/unicons.css
Seems to work

**Comment by Unknow-max** [comment]
Strange things happen.

**Comment by GrahamSH-LLK** [comment]
Try line.css, it seems to work

**Comment by deepakbhatti889** [comment]
> https://unicons.iconscout.com/release/v2.1.0/css/unicons.css

yes it works

**Comment by rohitornots** [comment]
`<link rel="stylesheet" href="https://unicons.iconscout.com/release/v2.1.0/css/unicons.css">`
Use this and it'll work :)

**Comment by AdnanDervisevic** [comment]
But why does only 2.1.0 work? The README states that you should use v4.0.0, which gives me a 403 as I try to access it, but as comments here are saying, 2.1.0 works. Would really appreciate some clarity from maintainers here if we are doing something wrong!

**Comment by imzedi** [comment]
@coderkali, Please use the latest version of Unicons. While writing this comment, So the latest version is `4.0.8`.

As this is a major update, the old way of using Unicons won't work with the latest version. Please follow the guidelines here for the latest version [here](https://help.iconscout.com/hc/en-gb/articles/13811255780889-How-to-use-Unicons)
