### ISSUE TITLE
Fonts folder missing in v3.0.4

### ISSUE THREAD

**Issue by EgoistDeveloper** [Iconscout/unicons#120]
CSS icons not loading in v3.0.4 because fonts folder and contains missing. But v3.0.0 working properly. I think forgotten.

I am using NPM.

**Comment by tarunmangukiya** [comment]
Hi @EgoistDeveloper, Can you check it with latest release?

**Comment by victorvuelma** [comment]
I was having the same problem, resolved on latest release

**Comment by EgoistDeveloper** [comment]
@tarunmangukiya yes, it is working now. Thanks.
