### ISSUE TITLE
As NPM package

### ISSUE THREAD

**Issue by antonreshetov** [Iconscout/unicons#13]
Since there are libraries that now depend on unicons, it is good to be able to install unicons via NPM instead of direct downloading from github - `github:iconscout/unicons#master`.
It will also be possible to specify the required version.

**Comment by tarunmangukiya** [comment]
Hi @antonreshetov,

Thanks for the suggestion. I've published it as a package at https://www.npmjs.com/package/@iconscout/unicons. Hope this works!
