### ISSUE TITLE
OTS parsing error

### ISSUE THREAD

**Issue by 7aklhz** [Iconscout/unicons#138]
Hi, 

I'm using uicons with jsdelivr. Lately, I'm getting the following errors 
`dashboard:1 Failed to decode downloaded font: https://cdn.jsdelivr.net/npm/@iconscout/unicons@4.0.0/fonts/line/unicons-6.woff2
dashboard:1 OTS parsing error: invalid sfntVersion: 1936028172
dashboard:1 Failed to decode downloaded font: https://cdn.jsdelivr.net/npm/@iconscout/unicons@4.0.0/fonts/line/unicons-9.woff2
dashboard:1 OTS parsing error: invalid sfntVersion: 4008750
dashboard:1 Failed to decode downloaded font: https://cdn.jsdelivr.net/npm/@iconscout/unicons@4.0.0/fonts/line/unicons-3.woff2
dashboard:1 OTS parsing error: invalid sfntVersion: -369077877
dashboard:1 Failed to decode downloaded font: https://cdn.jsdelivr.net/npm/@iconscout/unicons@4.0.0/fonts/line/unicons-11.woff2
dashboard:1 OTS parsing error: invalid sfntVersion: 1110126000`

Please advise. 

Cheers

**Comment by rosiecakes** [comment]
hey 7aklhz, any luck with this issue?

**Comment by 7aklhz** [comment]
nope... still there

**Comment by rosiecakes** [comment]
thanks. console is just full of warnings. using v3.0.1 for now

**Comment by OceanAbernathy** [comment]
Same problem

**Comment by Galaxy-Coding** [comment]
Same problem - I'm using v4.0.0

**Comment by pjotrs-osnovskis** [comment]
Same problem!

**Comment by lacakp** [comment]
same problem v4.0.0

**Comment by 7aklhz** [comment]
@tarunmangukiya: any news on this please ?

**Comment by Rope-a-dope** [comment]
Same problem here.

**Comment by tacman** [comment]
Any chance of a fix?  Sure, it's not urgent, but because it fills up the console with warnings it makes it easy to miss other warnings.

**Comment by QkeleQ10** [comment]
Still an issue! Please fix

**Comment by bialka104b** [comment]
I also have this problem in unicons 4.0.0
I decided to swap version 4 for version 3.

**Comment by daGUY** [comment]
I’m having the exact same issue with 4.0.1. I’m referencing the CSS and font files locally, but I know the paths and everything are correct because the icons display correctly, yet I get the “OTS parsing error” for all .woff2 fonts.

**Comment by jakubdura** [comment]
Same problem. v4.0.0 line
Chrome: " Failed to decode downloaded font: "
Mozilla: "downloadable font: rejected by sanitizer "

**Comment by SABBIR657** [comment]
any solution?

**Comment by Steven-zion** [comment]
has anyone fixed this yet without downgrading the version

**Comment by YvanL** [comment]
@tarunmangukiya Any news regarding this issue?

**Comment by farzadso** [comment]
Any way we can fix this? If you point us in the right direction, we might be able to contribute and fix it ourselves and open a PR for it @tarunmangukiya

**Comment by imzedi** [comment]
Fixed this issue in the latest patch
please use the latest version `4.0.8` and that will solve this issue.

The actual PR of the fix is #176 which is released with v4.0.8
