### ISSUE TITLE
Monochrome svgs are solid black

### ISSUE THREAD

**Issue by armstrongnate** [Iconscout/unicons#152]
All of the svgs in the monochrome directory are solid black. Is that intentional? Is there some way to generate the monochrome svgs variants without using a React component?

**Comment by imzedi** [comment]
Hey @armstrongnate,

Monochrome SVGs are being modified on the fly.
You can check scripts [https://github.com/Iconscout/unicons/tree/master/scripts/monochrome](here) that are doing this.

For now, If you need monochromed SVG, you can download it from [https://iconscout.com/unicons/explore/monochrome](here) single file as well as the whole bundle.

Please feel free to re-open this issue if still need any help!
Thanks.
