### ISSUE TITLE
arrow.svg not included in npm

### ISSUE THREAD

**Issue by jakobrosenberg** [Iconscout/unicons#22]
Following path does not exist:
@iconscout/unicons/svg/arrow.svg

**Comment by tarunmangukiya** [comment]
Hi @jakobrosenberg, in latest update we've changed the path to `@iconscout/unicons/svg/line/arrow.svg`.

Please change it accordingly. We've done this as we'll be launching new styles in upcoming months.

Regrets for inconvenience.
