### ISSUE TITLE
Line break in path in chart-pie-alt.svg

### ISSUE THREAD

**Issue by antonreshetov** [Iconscout/unicons#4]
For rendering SVG in browser doesn't matter, but for my lib for Vue https://github.com/antonreshetov/vue-unicons I parse SVG path and store it in vars, and on this icon there is a problem

**Comment by tarunmangukiya** [comment]
Fixed in master: https://raw.githubusercontent.com/Iconscout/unicons/master/svg/chart-pie-alt.svg
