### ISSUE TITLE
SVG images not aligned?

### ISSUE THREAD

**Issue by engelfrost** [Iconscout/unicons#41]
Hi, 

It seems that the SVG images are not positioned consistently within the canvas

![image](https://user-images.githubusercontent.com/11315/72898021-8e5f9580-3d23-11ea-9007-1303df455542.png)

It looks like the content is centered, without considering variants of the same icon (in the example above: image-plus and image-minus). 

Is there any way this can be fixed?

**Comment by tarunmangukiya** [comment]
Hmm that's strange. You can manually update them by editing the SVG. Meanwhile, can you please write your request at https://discuss.iconscout.com/ so that our team can pick up that issue and resolve that in next release?

**Comment by tarunmangukiya** [comment]
Hi @engelfrost, we've fixed this issue. You can try it out at https://iconscout.com/unicons/explore/line
