### ISSUE TITLE
Document changed icons

### ISSUE THREAD

**Issue by cypressious** [Iconscout/unicons#53]
After upgrading I noticed that some icon names have changed, e.g. `code` and `location`. Please document changed names in the release notes.

**Comment by tarunmangukiya** [comment]
Hi @cypressious,

Thank you for drawing attention. I am writing release note. I'll get back to you by tomorrow/day after tomrrow. 

Meanwhile, you can search icons at https://iconscout.com/unicons. It'll make you easy to find icons.

**Comment by tarunmangukiya** [comment]
Hi @cypressious,

Please find the icon name change at https://github.com/Iconscout/unicons/releases/tag/v2.1.3
