### ISSUE TITLE
Icons not loading

### ISSUE THREAD

**Issue by SkyleKayma** [Iconscout/unicons#64]
Hi,

Icons from unicons are not loading.
On chrome and firefox everything load correctly except renders, and with edge, nothing shows up.

Please take a look : 
https://iconscout.com/unicons/explore/line

![image](https://user-images.githubusercontent.com/17049216/79030657-5d606580-7b9a-11ea-8165-ae0e1c3d9e3f.png)

Thx !

**Comment by alwex** [comment]
i am having the exact same issue, firefox and chrome

**Comment by tarunmangukiya** [comment]
Hi @SkyleKayma & @alwex,

We've fixed this issue, can you check and confirm it?

**Comment by SkyleKayma** [comment]
Everything is working now. Perfect ! 👍

**Comment by tarunmangukiya** [comment]
Thanks for reporting @SkyleKayma @alwex.
We've fixed the issue.
