### ISSUE TITLE
Combining Icon files

### ISSUE THREAD

**Issue by zahedulhossain** [Iconscout/unicons#65]
How can I combine all the separate font files into one bundle ?

**Comment by tarunmangukiya** [comment]
Hey @zahedulhossain, were you able to solve this?

**Comment by zahedulhossain** [comment]
Not exactly. I closed this because I realized I was stupid and doing it wrong. My purpose was to change some font styling.

**Comment by zahedulhossain** [comment]
Not exactly. I didn't get any response so I closed this and wrote some extra css, but would have been nice if I could import and serve only one font file, rather then 37.

**Comment by zahedulhossain** [comment]
Not exactly. I wrote some extra css, but would have been nice if I could import only one font file.
