### ISSUE TITLE
Clock icon not center aligned

### ISSUE THREAD

**Issue by adarsh4d** [Iconscout/unicons#66]
![image](https://user-images.githubusercontent.com/28686122/79371676-5eb2d900-7f72-11ea-85d0-d73f061135e1.png)

Some of the clock icons are not center-aligned horizontally.

**Comment by tarunmangukiya** [comment]
Hi @adarsh4d Can you check the updated icon at https://iconscout.com/unicons/explore/line?

**Comment by adarsh4d** [comment]
Unfortunately its still the same, 
![image](https://user-images.githubusercontent.com/28686122/80589796-80af5f80-8a38-11ea-9583-79db8fc6e13f.png)

By the way nice addition of coy hex and Unicode button 👍

**Comment by tarunmangukiya** [comment]
You can download it now, have fixed it.

![image](https://user-images.githubusercontent.com/12470086/80977287-26e8d400-8e42-11ea-8a3a-f55fca14724f.png)

Also, if you're designer you can use our desktop app or plugin to get Unicons right inside Figma.
