### ISSUE TITLE
JSON file with icons name and its hexa/unicode

### ISSUE THREAD

**Issue by fabiwerneck** [Iconscout/unicons#69]
Just like FontAwesome, it would be very helpful to have a json containing all icon's unicodes.

E.g. based on json file you already have on GitHub:

```
{
    "id": 1213915,
    "name": "comment-alt-question",
    "svg": "svg/line/comment-alt-question.svg",
    "category": "Chat",
    "style": "Line",
    "tags": [
        "question-mark-chat-bubble",
        "chat",
        "chat-bubble",
        "help-chat",
        "support-chat",
        "comment-alt-question"
    ],
    "unicode": "f26e"
}
```

Thanks :)

**Comment by tarunmangukiya** [comment]
Hi @fabiwerneck,

Can you try https://unicons.iconscout.com/release/v2.1.7/json/line.json and download fonts from https://github.com/Iconscout/unicons/releases?

**Comment by tarunmangukiya** [comment]
Hi @fabiwerneck, we've released a new update to Iconscout. Check it out here: https://iconscout.com/unicons/explore/line

**Comment by fabiwerneck** [comment]
Hey @tarunmangukiya,
It worked 🎉
Thank you!!!!
